/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.ndipatri.kmp.openapi.particle.models


import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * A device variable has been retrieved.
 *
 * @param result 
 */
@Serializable

data class DeviceVariableResult (

    @SerialName(value = "result") val result: kotlin.String? = null

) {


}

