/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.ndipatri.kmp.openapi.particle.models


import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * A device has been retrieved.
 *
 * @param id 
 * @param name 
 * @param owner 
 * @param lastIpAddress 
 * @param lastHeard 
 * @param lastHandshakeAt 
 * @param productId 
 * @param online 
 * @param platformId 
 * @param cellular 
 * @param notes 
 * @param functions 
 * @param variables 
 * @param status 
 * @param serialNumber 
 * @param iccid 
 * @param imei 
 * @param macWifi 
 * @param mobileSecret 
 * @param systemFirmwareVersion 
 * @param firmwareUpdatesEnabled 
 * @param firmwareUpdatesForced 
 * @param deviceProtection 
 */
@Serializable

data class DeviceGetResponse (

    @SerialName(value = "id") val id: kotlin.String? = null,

    @SerialName(value = "name") val name: kotlin.String? = null,

    @SerialName(value = "owner") val owner: kotlin.String? = null,

    @SerialName(value = "last_ip_address") val lastIpAddress: kotlin.String? = null,

    @SerialName(value = "last_heard") val lastHeard: kotlin.String? = null,

    @SerialName(value = "last_handshake_at") val lastHandshakeAt: kotlin.String? = null,

    @SerialName(value = "product_id") val productId: kotlin.Int? = null,

    @SerialName(value = "online") val online: kotlin.Boolean? = null,

    @SerialName(value = "platform_id") val platformId: kotlin.Int? = null,

    @SerialName(value = "cellular") val cellular: kotlin.Boolean? = null,

    @SerialName(value = "notes") val notes: kotlin.String? = null,

    @SerialName(value = "functions") val functions: kotlin.collections.List<kotlin.String>? = null,

    @SerialName(value = "variables") val variables: kotlin.collections.List<kotlin.String>? = null,

    @SerialName(value = "status") val status: kotlin.String? = null,

    @SerialName(value = "serial_number") val serialNumber: kotlin.String? = null,

    @SerialName(value = "iccid") val iccid: kotlin.String? = null,

    @SerialName(value = "imei") val imei: kotlin.String? = null,

    @SerialName(value = "mac_wifi") val macWifi: kotlin.String? = null,

    @SerialName(value = "mobile_secret") val mobileSecret: kotlin.String? = null,

    @SerialName(value = "system_firmware_version") val systemFirmwareVersion: kotlin.String? = null,

    @SerialName(value = "firmware_updates_enabled") val firmwareUpdatesEnabled: kotlin.Boolean? = null,

    @SerialName(value = "firmware_updates_forced") val firmwareUpdatesForced: kotlin.Boolean? = null,

    @SerialName(value = "device_protection") val deviceProtection: kotlin.collections.Map<kotlin.String, kotlin.String>? = null

) {


}

