/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.ndipatri.kmp.openapi.particle.models


import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * A device function has been executed.
 *
 * @param id 
 * @param name 
 * @param connected 
 * @param returnValue 
 */
@Serializable

data class DeviceFunctionResponse (

    @SerialName(value = "id") val id: kotlin.String? = null,

    @SerialName(value = "name") val name: kotlin.String? = null,

    @SerialName(value = "connected") val connected: kotlin.Boolean? = null,

    @SerialName(value = "return_value") val returnValue: kotlin.Int? = null

) {


}

