/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.ndipatri.kmp.openapi.particle.models


import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * 
 *
 * @param arg 
 * @param format 
 */
@Serializable

data class FunctionRequestBodyValue (

    @SerialName(value = "arg") val arg: kotlin.String? = null,

    @SerialName(value = "format") val format: kotlin.String? = null

) {


}

